version: '3.1'

services:
  support-core:
    build: core/.
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: support-core-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: support_db
    volumes:
      - ./core/site:/var/www/html

  support-core-db:
    image: mariadb:5.5.56
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/mysql

  db-admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8181:80
    environment:
      PMA_HOST: support-core-db
